{{- range .Values.apps }}
{{- if .secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-secret
  namespace: {{ $.Values.global.namespace }}
type: Opaque
data:
  {{- range $key, $value := .secrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
{{- end }}