apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eshop-ingress
  namespace: {{ $.Values.global.namespace }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - app.eshop.local
        - api.eshop.local
        - id.eshop.local
      secretName: eshop-tls
  rules:
    - host: app.eshop.local
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: web-client-clusterip
                port:
                  number: 80
    - host: api.eshop.local
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: yarp-api-gateway-clusterip
                port:
                  number: 8080
    - host: id.eshop.local
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: keycloak-clusterip
                port:
                  number: 8080
